# Generated by Django 3.2 on 2023-04-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsRecipe',
            new_name='RecipeIngredient',
        ),
    ]
