# Generated by Django 3.2 on 2023-04-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230427_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, help_text='Введите название ингредиента', max_length=200, verbose_name='Название ингредиента'),
        ),
    ]
