# Generated by Django 3.2 on 2023-05-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_unique_author_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_author_recipe',
        ),
    ]
