# Generated by Django 3.2 on 2023-05-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_recipe_unique_author_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузить фото рецепта', upload_to='media/', verbose_name='Фото рецепта'),
        ),
    ]
