# Generated by Django 3.2 on 2023-05-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузить фото рецепта', upload_to='recipe_pics/', verbose_name='Фото рецепта'),
        ),
    ]
