services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: retrogm/foodgram_back:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static_back/
      - media_value:/app/media_back/
  frontend:
    image: retrogm/foodgram_front:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_back/
      - media_value:/var/html/media_back/

    depends_on:
      - backend
      - frontend

volumes:
  db_value:
  static_value:
  media_value:
